#+TITLE: lunanode-cli

* About

This is my fun project for studying and practicing lisp while building something
potentially useful.

* Installation

** Requirements

  - ~sbcl~ >= 2.2.6 (and quicklisp)
  - ~make~ >= 4.3

** Building

There are no release mechanism in-place yet, so please build ~lunanode-cli~ with
a simple make command:

#+begin_src shell
  make bin/lunanode-cli
#+end_src

** Installing

Once the binary is built, the ~install~ target can copy the binary to
~$HOME/.local/bin~ path.

#+begin_src shell
  make install
#+end_src

It is also possible to have shell completion in zsh by dumping the completion
script somewhere in a *$FPATH* directory.

*personal note*: not sure if I would recommend this, but I've been dumping all
my completion scripts into /$HOME/.oh-my-zsh/cache/completions/ and letting
[[https://github.com/ohmyzsh/ohmyzsh][oh-my-zsh]] source them.

#+begin_src shell
  lunanode-cli completion zsh > ~/.oh-my-zsh/cache/completions/_lunanode-cli
#+end_src

* Usage

The credentials to access lunanode services can be provided in any of the
following ways:
  - a credentials file, e.g: ~/.config/lunanode-cli/credentials.json
  - a set of environment variables, *$API_ID* and *$API_KEY*.
  - via command-line arguments (not recommended).

Only a few of the lunanode service interfaces have been implemented as commands,
notably some operations on the /virtualmachine/, /sshkey/ and /image/ services.

#+begin_src text
NAME:
  lunanode-cli - A command-line interface program for interacting with lunanode cloud services.

USAGE:
  lunanode-cli [global-options] [<command>] [command-options] [arguments ...]

  A CLI program for interfacing  with lunanode cloud services.

OPTIONS:
      --api-id <VALUE>   API ID [env: $API_ID]
      --api-key <VALUE>  API KEY [env: $API_KEY]
      --help             display usage information and exit
      --version          display version and exit

COMMANDS:
  virtualmachine  interact with the virtual machine service.
  image           interact with the images service.
  sshkey          interact with the sshkeys service.
  ssh             ssh into a virtual machine.
  plan            list pricing plans.
  billing         interact with the billing service.
  completion      generate shell completion scripts.

AUTHORS:
  August Feng <augustfengd@gmail.com>

LICENSE:
  BSD 2-Clause
#+end_src

